<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\FrenetRatesConversion\Model;

use Frenet\ObjectType\Entity\Shipping\Quote\Service;
use Frenet\Shipping\Service\RateRequestProvider;
use MagedIn\FrenetRatesConversion\Model\Validator\ServiceConversionValidator;
use Psr\Log\LoggerInterface;

class ServiceProcessor
{
    /**
     * @var RateRequestProvider
     */
    private $rateRequestProvider;

    /**
     * @var ServiceConversionValidator
     */
    private $conversionValidator;

    /**
     * @var ServicePriceConverterInterface
     */
    private $priceConverter;

    /**
     * @var LoggerInterface
     */
    private $logger;

    public function __construct(
        RateRequestProvider $rateRequestProvider,
        ServiceConversionValidator $conversionValidator,
        ServicePriceConverterInterface $priceConverter,
        LoggerInterface $logger
    ) {
        $this->rateRequestProvider = $rateRequestProvider;
        $this->conversionValidator = $conversionValidator;
        $this->priceConverter = $priceConverter;
        $this->logger = $logger;
    }

    /**
     * @param Service $service
     *
     * @return Service
     */
    public function process(Service $service): Service
    {
        if (!$this->conversionValidator->validate($service)) {
            return $service;
        }

        try {
            $convertedPrice = $this->priceConverter->convert($service->getShippingPrice());
            $service->setData('shipping_price', $convertedPrice);
        } catch (\Exception $e) {
            $this->logger->error($e);
        }
        return $service;
    }
}
