<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\FrenetRatesConversion\Model\Validator;

use Frenet\ObjectType\Entity\Shipping\Quote\Service;

interface ServiceValidatorInterface
{
    /**
     * @param Service $service
     *
     * @return bool
     */
    public function validate(Service $service): bool;
}
