<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\FrenetRatesConversion\Model\Validator\Service;

use Frenet\ObjectType\Entity\Shipping\Quote\Service;
use MagedIn\FrenetRatesConversion\Model\Config;
use MagedIn\FrenetRatesConversion\Model\Validator\ServiceValidatorInterface;

class AllowedServiceValidator implements ServiceValidatorInterface
{
    /**
     * @var Config
     */
    private $config;

    public function __construct(
        Config $config
    ) {
        $this->config = $config;
    }

    /**
     * @inheritDoc
     */
    public function validate(Service $service): bool
    {
        return in_array($service->getServiceCode(), $this->config->getAllowedServiceCodes());
    }
}
