<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\FrenetRatesConversion\Model\Validator\Service;

use Frenet\ObjectType\Entity\Shipping\Quote\Service;
use Frenet\Shipping\Service\RateRequestProvider;
use MagedIn\FrenetRatesConversion\Model\Config;
use MagedIn\FrenetRatesConversion\Model\Validator\ServiceValidatorInterface;
use Magento\Framework\Exception\LocalizedException;

class DestinyCountryValidator implements ServiceValidatorInterface
{
    /**
     * @var RateRequestProvider
     */
    private $rateRequestProvider;

    /**
     * @var Config
     */
    private $config;

    public function __construct(
        RateRequestProvider $rateRequestProvider,
        Config $config
    ) {
        $this->rateRequestProvider = $rateRequestProvider;
        $this->config = $config;
    }

    /**
     * @param Service $service
     *
     * @return bool
     */
    public function validate(Service $service): bool
    {
        try {
            $rateRequest = $this->rateRequestProvider->getRateRequest();
        } catch (LocalizedException $e) {
            return false;
        }

        /**
         * USD quotation values are only present when the destiny country is outside Brazil, for instance.
         * If the destiny country is Brazil, for instance, then we cannot convert the value.
         */
        $notAllowed = $this->config->getNotConvertibleCountries();
        if (!$service->getServiceCode() || in_array($rateRequest->getDestCountryId(), $notAllowed)) {
            return false;
        }

        return true;
    }
}
